### ISSUE TITLE
No LICENSE?

### ISSUE THREAD

**Issue by waddlesplash** [kode54/playptmod#1]
There is no LICENSE listed anywhere in the repository. eightbitbubsy's code is Public Domain (according to the SourceForge project page), what are your modifications/original code licensed under?

**Comment by kode54** [comment]
I have added a BSD 3 clause license to this repository. It should be more friendly for some places that do not have a concept of Public Domain.

**Comment by waddlesplash** [comment]
Thanks, that works.
